server:
  error:
    include-stacktrace: on-param
    
## Conecxão com o banco de dados
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onbox_database?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
